fix [script]: fix install

diff --git a/mini-app/SynoBuildConf/install b/mini-app/SynoBuildConf/install
--- a/mini-app/SynoBuildConf/install
+++ b/mini-app/SynoBuildConf/install
@@ -1,6 +1,8 @@
 #!/bin/bash
 # Copyright (C) 2000-2020 Synology Inc. All rights reserved.
 
+set -e
+
 ### Use PKG_DIR as working directory.
 PKG_DIR=/tmp/_test_spk
 rm -rf $PKG_DIR
@@ -10,37 +12,66 @@ mkdir -p $PKG_DIR
 source /pkgscripts/include/pkg_util.sh
 
 create_package_tgz() {
-    local firewere_version=
     local package_tgz_dir=/tmp/_package_tgz
     local binary_dir=$package_tgz_dir/usr/local/bin
 
     ### clear destination directory
     rm -rf $package_tgz_dir && mkdir -p $package_tgz_dir
 
-    ### install needed file into PKG_DIR
+    ### install demo binary
     mkdir -p $binary_dir
-    cp -av demo $binary_dir
-    make install DESTDIR="$package_tgz_dir" INSTALLDIR="$package_tgz_dir"
-    make packageinstall DESTDIR="$package_tgz_dir" PKG_DIR="$PKG_DIR"
+    if [ -f ../demo ]; then
+        cp -av ../demo $binary_dir
+        chmod 755 $binary_dir/demo
+    else
+        echo "Error: demo binary not found!"
+        exit 1
+    fi
 
-    ### create package.tgz $1: source_dir $2: dest_dir
+    ### create package.tgz
     pkg_make_package $package_tgz_dir "${PKG_DIR}"
 }
 
 create_spk(){
-    cp -av scripts $PKG_DIR/scripts
-    cp -av PACKAGE_ICON*.PNG $PKG_DIR
-    cp -av conf $PKG_DIR
-    cp -av LICENSE $PKG_DIR
+    # Copy scripts if they exist
+    if [ -d ../script ]; then
+        cp -av ../script $PKG_DIR/scripts
+    elif [ -d ../scripts ]; then
+        cp -av ../scripts $PKG_DIR/scripts
+    fi
+    
+    # Copy icons
+    if ls ../PACKAGE_ICON*.PNG 1> /dev/null 2>&1; then
+        cp -av ../PACKAGE_ICON*.PNG $PKG_DIR
+    fi
+    
+    # Copy conf
+    if [ -d ../conf ]; then
+        cp -av ../conf $PKG_DIR
+    fi
 
-    ./INFO.sh > INFO
-    cp INFO $PKG_DIR/INFO
+    # Generate INFO file (from root directory)
+    if [ -f ../INFO.sh ]; then
+        cd ..
+        ./INFO.sh > INFO
+        cp INFO $PKG_DIR/INFO
+        cd SynoBuildConf
+    else
+        echo "Warning: INFO.sh not found in parent directory"
+        # Create minimal INFO file
+        cat > $PKG_DIR/INFO << 'EOF'
+package="mini-app"
+version="1.0.0"
+arch="x86_64"
+maintainer="Your Name"
+distributor="Your Name"
+description="Demo package for Synology DSM"
+EOF
+    fi
 
-    ### Create the final spk.
-    # pkg_make_spk <source path> <dest path> <spk file name>
-    # Please put the result spk into /image/packages
-    # spk name functions: pkg_get_spk_name pkg_get_spk_unified_name pkg_get_spk_family_name
+    ### Create the final spk
     mkdir -p /image/packages
+    echo "Creating SPK package..."
     pkg_make_spk ${PKG_DIR} "/image/packages" $(pkg_get_spk_family_name)
 }
 
